resources:
  - name: platform-automation-tasks
    type: s3
    source:
      access_key_id: ((access_key_id))
      secret_access_key: ((secret_access_key))
      endpoint: ((endpoint))
      bucket: ((bucket))
      skip_ssl_verification: true
      regexp: .*tasks-(.*).zip

  - name: platform-automation-image
    type: s3
    source:
      access_key_id: ((access_key_id))
      secret_access_key: ((secret_access_key))
      endpoint: ((endpoint))
      bucket: ((bucket))
      skip_ssl_verification: true
      regexp: .*image-(.*).tgz

  # - name: installation
  #   type: s3
  #   source:
  #     access_key_id: ((access_key_id))
  #     secret_access_key: ((secret_access_key))
  #     endpoint: ((endpoint))
  #     bucket: ((bucket))
  #     skip_ssl_verification: true
  #     regexp: installation-(.*).zip

  - name: opsman-image
    type: s3
    source:
      access_key_id: ((access_key_id))
      secret_access_key: ((secret_access_key))
      endpoint: ((endpoint))
      bucket: ((binaries_bucket))
      skip_ssl_verification: true
      regexp: "PCF/ops-manager/pcf-vsphere-(.*).ova" #regexp: ((opsman_image_s3_versioned_regexp)) # vsphere ex: pcf-vsphere-(.*).ova


  # configurations
  - name: configuration
    type: git
    source:
      uri: ((github_repo))
      branch: ((github_branch))
      username: ((github_username))
      password: ((github_token))
      paths: ((foundation))

  - name: variable
    type: git
    source:
      uri: ((github_repo))
      branch: ((github_branch))
      username: ((github_username))
      password: ((github_token))
      paths: var

  # triggers used to have jobs do something in a timely manner
  - name: one-time-trigger
    type: time
    source:
      interval: 999999h
  #
  # - name: daily-trigger
  #   type: time
  #   source:
  #     interval: 24h

jobs:
  - name: install-opsman
    serial: true
    serial_groups: [ install ]
    plan:
      - aggregate:
          - get: platform-automation-image
            params:
              unpack: true
          - get: one-time-trigger
            trigger: true
          - get: platform-automation-tasks
            params:
              unpack: true
          - get: opsman-image
          - get: configuration
          - get: variable
      - task: create-vm
        image: platform-automation-image
        file: platform-automation-tasks/tasks/create-vm.yml
        input_mapping:
          image: opsman-image
          state: configuration
          config: configuration
          vars: variable
        params:
          VARS_FILES: vars/((foundation))/vars/opsman-vars.yml
          STATE_FILE: ((foundation))/state/state.yml
          OPSMAN_CONFIG_FILE: ((foundation))/config/opsman.yml
        ensure: &make-state-commit
          do:
            - task: make-commit
              image: platform-automation-image
              file: platform-automation-tasks/tasks/make-git-commit.yml
              input_mapping:
                repository: configuration
                file-source: generated-state
              output_mapping:
                repository-commit: configuration-commit
              params:
                FILE_SOURCE_PATH: state.yml
                FILE_DESTINATION_PATH: ((foundation))/state/state.yml
                GIT_AUTHOR_EMAIL: "pcf-pipeline-bot@example.com"
                GIT_AUTHOR_NAME: "Platform Automation Bot"
                COMMIT_MESSAGE: 'Update state file'
            - put: configuration
              params:
                repository: configuration-commit
                merge: true
      - task: configure-authentication
        image: platform-automation-image
        file: platform-automation-tasks/tasks/configure-authentication.yml
        attempts: 10
        input_mapping:
          env: configuration
          config: configuration
        params:
          ENV_FILE: ((foundation))/env/env.yml
          AUTH_CONFIG_FILE: ((foundation))/config/auth.yml
      - task: configure-director
        image: platform-automation-image
        file: platform-automation-tasks/tasks/configure-director.yml
        input_mapping:
          config: configuration
          env: configuration
          vars: variable
        params:
          VARS_FILES: vars/((foundation))/vars/director-vars.yml
          ENV_FILE: ((foundation))/env/env.yml
          DIRECTOR_CONFIG_FILE: ((foundation))/config/director.yml
      - task: apply-director-changes
        image: platform-automation-image
        file: platform-automation-tasks/tasks/apply-director-changes.yml
        input_mapping:
          env: configuration
        params:
          ENV_FILE: ((foundation))/env/env.yml

  - name: staged-director-config
    serial: true
    plan:
      - aggregate:
          - get: platform-automation-tasks
            params: {unpack: true}
          - get: platform-automation-image
            params: {unpack: true}
          - get: configuration
      - task: staged-director-config
        image: platform-automation-image
        file: platform-automation-tasks/tasks/staged-director-config.yml
        input_mapping:
          env: configuration
        params:
          ENV_FILE: ((foundation))/env/env.yml
