resources:
 - name: pipelines-repo
   type: git
   source:
     uri: ((github_repo))
     branch: ((github_branch))
     username: ((github_username))
     password: ((github_token))

 # configurations
 - name: configuration
   type: git
   source:
     uri: ((config_github_repo))
     branch: ((config_github_branch))
     username: ((github_username))
     password: ((github_token))

jobs:
 - name: add-vm-extensions
   plan:
   - aggregate:
     - get: pipelines-repo
     - get: configuration
   - task: add-vm-extensions
     image: platform-automation-image
     file: pipelines-repo/tasks/add-vm-extensions/task.yml
     input_mapping:
       env: configuration
     params:
       OPS_MAN_FQDN: ((target))
