az-configuration:
- name: PAS-MGMT
  clusters:
  - cluster: attic
    resource_pool: PAS-MGMT
  iaas_configuration_guid: 9aeef05aef44ca46134a
- name: AZ1
  clusters:
  - cluster: attic
    resource_pool: PAS
  iaas_configuration_guid: 9aeef05aef44ca46134a
- name: AZ2
  clusters:
  - cluster: attic
    resource_pool: PAS
  iaas_configuration_guid: 9aeef05aef44ca46134a
- name: AZ3
  clusters:
  - cluster: attic
    resource_pool: PAS
  iaas_configuration_guid: 9aeef05aef44ca46134a
network-assignment:
  network:
    name: PAS-INFRA
  other_availability_zones: []
  singleton_availability_zone:
    name: PAS-MGMT
networks-configuration:
  icmp_checks_enabled: true
  networks:
  - name: PAS-INFRA
    subnets:
    - iaas_identifier: pas-infra
      cidr: 172.16.21.0/24
      dns: 192.168.100.50,192.168.100.150
      gateway: 172.16.21.1
      reserved_ip_ranges: 172.16.21.1-172.16.21.20
      availability_zone_names:
      - PAS-MGMT
      - AZ1
      - AZ2
      - AZ3
  - name: PAS-DEPLOY
    subnets:
    - iaas_identifier: pas-deploy
      cidr: 172.16.22.0/24
      dns: 192.168.100.50,192.168.100.150
      gateway: 172.16.22.1
      reserved_ip_ranges: 172.16.22.1-172.16.22.20
      availability_zone_names:
      - PAS-MGMT
      - AZ1
      - AZ2
      - AZ3
  - name: PAS-SERVICES
    subnets:
    - iaas_identifier: pas-services
      cidr: 172.16.23.0/24
      dns: 192.168.100.50,192.168.100.150
      gateway: 172.16.23.1
      reserved_ip_ranges: 172.16.23.1-172.16.23.20
      availability_zone_names:
      - AZ1
      - AZ2
      - AZ3
  - name: PAS-DYNSVC
    subnets:
    - iaas_identifier: pas-dynsvc
      cidr: 172.16.24.0/24
      dns: 192.168.100.50,192.168.100.150
      gateway: 172.16.24.1
      reserved_ip_ranges: 172.16.24.1-172.16.24.20
      availability_zone_names:
      - AZ1
      - AZ2
      - AZ3
properties-configuration:
  director_configuration:
    blobstore_type: local
    bosh_recreate_on_next_deploy: false
    bosh_recreate_persistent_disks_on_next_deploy: false
    database_type: internal
    director_worker_count: 5
    encryption:
      keys: []
      providers: []
    hm_emailer_options:
      enabled: false
    hm_pager_duty_options:
      enabled: false
    identification_tags: {}
    job_configuration_on_tmpfs: false
    keep_unreachable_vms: false
    local_blobstore_options:
      tls_enabled: true
    max_threads: 8
    ntp_servers_string: 192.168.1.1
    post_deploy_enabled: true
    resurrector_enabled: false
    retry_bosh_deploys: false
    skip_director_drain: false
  dns_configuration:
    excluded_recursors: []
    handlers: []
  security_configuration:
    generate_vm_passwords: true
    opsmanager_root_ca_trusted_certs: true
  syslog_configuration:
    address: syslog.ragazzilab.com
    enabled: true
    forward_debug_logs: false
    port: "514"
    tls_enabled: false
    transport_protocol: udp
resource-configuration:
  compilation:
    instances: automatic
    instance_type:
      id: automatic
  director:
    instances: automatic
    persistent_disk:
      size_mb: automatic
    instance_type:
      id: automatic
vmextensions-configuration: []
