---
opsman-configuration:
  vsphere:
    vcenter:
      url: corevcsa.ragazzilab.com
      username: administrator@vsphere.local
      password: VMware1!
      datastore: EQL-THIN01
      ca_cert: certificate
      host:                      # vCenter host to deploy Ops Manager in
      datacenter: LAB
      resource_pool: /LAB/host/attic/Resources/PAS-MGMT # or /<Data Center Name>/host/<Cluster Name>
      folder: BOSH/PAS/VMs
      insecure: 1                            # default: 0 (secure); 1 (insecure)
    disk_type: thin                          # example: thin|thick
    private_ip: 172.16.21.20
    dns: 192.168.1.1
    ntp: 192.168.1.1                     # example: ntp.ubuntu.com
    ssh_password: VMware1!
    ssh_public_key:            # for OpsManager >= 2.3
    hostname: om.pas.ragazzilab.com
    network: pas-infra                 # vcenter network to deploy to
    netmask: 255.255.255.0
    gateway: 172.16.21.1
    vm_name: Ops_Manager                     # default: Ops_Manager
    memory: 8                                # default: 8 GB
    cpu: 1                                   # default: 1
