---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfplatformrecovery/bbr-pcf-pipeline-tasks
    tag: final

inputs:
  - name: bbr-pipeline-tasks-repo
    # Directory containing the bbr executable
  - name: binary

outputs:
    # Contains `director-backup.tar` artifact created by `bbr director backup`
  - name: director-backup-artifact

run:
  path: bash
  args:
  - "-c"
  - |
    set -eux

    # shellcheck disable=SC1090
    source "$(dirname "$0")/../../scripts/export-director-metadata"

    pushd director-backup-artifact
      ../binary/bbr director --host "${BOSH_ENVIRONMENT}" \
        --username "$BOSH_USERNAME" \
        --private-key-path <(echo "${BOSH_PRIVATE_KEY}") \
        backup

      tar -cvf director-backup.tar -- *
      # shellcheck disable=SC2086
      rm -rf ${BOSH_ENVIRONMENT}_*
    popd

params:
  # The Ops Manager URL, e.g. https://pcf.example.com
  OPSMAN_URL:

  # If true, SSL validation will be skipped when connecting to Ops Manager API
  SKIP_SSL_VALIDATION: false

  # Client credentials for Ops Manager API. If empty, user credentials will be used
  CLIENT_ID:
  CLIENT_SECRET:

  # User credentials for Ops Manager API
  OPSMAN_USERNAME:
  OPSMAN_PASSWORD:

  # The SSH private key for the Ops Manager VM
  # If provided, a SSH tunnel through the Ops Manager VM is created and used by bbr
  OPSMAN_PRIVATE_KEY:
