# The inputs, outputs, params, filename, and filepath
# of this task file are part of its semantically versioned API.
# See our documentation for a detailed discussion of our semver API.
# See www.semver.org for an explanation of semantic versioning.

# code_snippet configure-product start yaml
---
platform: linux

inputs:
- name: env # contains the env file with target OpsMan Information
-
params:
  ENV_FILE: env.yml
  # - Required
  # - Filepath of the env config YAML
  # - The path is relative to root of the `env` input

run:
  path: bash
  args:
  - "-c"
  - |
    set -euo pipefail

    status="$(om --env env/"${ENV_FILE}"  installations --format json | jq .[0].status)"
    trimmed_status="$(xargs <<< "$status")"

    if [ "$trimmed_status" == "running" ]; then
      echo "\"Apply Changes\" is in flight." | tee /dev/stderr
      exit 1
    fi

    echo "No \"Apply Changes\" in flight."
