---
platform: linux


inputs:
- name: config # contains the env file with target OpsMan Information
- name: vars # variable files to be made available
- name: secrets
  optional: true
- name: custom-tasks


params:
  NSXT_INFRA_CONFIG_FILE: nsx-infra.yml


run:
  path: bash
  args:
  - "-c"
  - |
    set -eu
    yq --version

    export NSXUSERNAME=$(yq eval '.nsxt_admin_username' $NSXT_INFRA_CONFIG_FILE )
    export NSXPASSWORD=$(yq eval '.nsxt_admin_password' $NSXT_INFRA_CONFIG_FILE )
    export NSXHOSTNAME=$(yq eval '.nsxt_manager' $NSXT_INFRA_CONFIG_FILE )

    #set -eux

    source custom-tasks/tasks/functions/nsxt4.sh
    source custom-tasks/tasks/functions/nsxt-yml.sh

    echo "Creating objects on NSX Manager: $NSXHOSTNAME"

    Create_T1_Gateways $NSXT_INFRA_CONFIG_FILE
    Create_Segments $NSXT_INFRA_CONFIG_FILE
    Create_IP_Pools $NSXT_INFRA_CONFIG_FILE
    Create_IP_Blocks $NSXT_INFRA_CONFIG_FILE
    Create_T0_NAT_Rules $NSXT_INFRA_CONFIG_FILE
    Create_LB_Monitors $NSXT_INFRA_CONFIG_FILE
    Create_LB_Pools  $NSXT_INFRA_CONFIG_FILE
    Create_Load_Balancers $NSXT_INFRA_CONFIG_FILE
    
