---
platform: linux


inputs:
- name: config # contains the env file with target OpsMan Information
- name: vars # variable files to be made available
- name: secrets
  optional: true
- name: custom-tasks


params:
  NSXT_INFRA_CONFIG_FILE: nsx-infra.yml


run:
  path: bash
  args:
  - "-c"
  - |
    set -eux

    export NSXUSERNAME=$(yq -t r $NSXT_INFRA_CONFIG_FILE 'nsxt_admin_username')
    export NSXPASSWORD=$(yq -t r $NSXT_INFRA_CONFIG_FILE 'nsxt_admin_password')



    source custom-tasks/tasks/functions/nsxt.sh
    source custom-tasks/tasks/functions/nsx-yml.sh

    Create_Logical_Switches $NSXT_INFRA_CONFIG_FILE
    Create_T1_Routers $NSXT_INFRA_CONFIG_FILE
    Create_T0_NAT_Rules $NSXT_INFRA_CONFIG_FILE
    Create_IP_Pools $NSXT_INFRA_CONFIG_FILE
    Create_IP_Blocks $NSXT_INFRA_CONFIG_FILE
    Create_Load_Balancers $NSXT_INFRA_CONFIG_FILE
