---
platform: linux


inputs:
- name: vars
- name: custom-tasks
- name: pks-cli

params:
  PKSCLUSTER_CONFIG_FILE: pks-clusters.yml
  PKS_VARS_FILE: pks-vars.yml
  SKIP_MISSING: true



run:
  path: bash
  args:
  - "-c"
  - |
    set -eux

    #source custom-tasks/tasks/functions/uaac.sh

    # get client name/secret from
    # run pks get clusters

    PKS_URL=$(om interpolate --config "vars/$PKS_VARS_FILE" --skip-missing  --path /properties_pks_api_hostname)

    PKS_CLIENT=$(om interpolate --config "vars/$PKSCLUSTER_CONFIG_FILE" --skip-missing --path /client_name)
    PKS_SECRET=$(om interpolate --config "vars/$PKSCLUSTER_CONFIG_FILE" --skip-missing --path /client_secret)

    PKSCLI="$(find pks-cli/*pks-linux-amd64* 2>/dev/null | head -n1)"
    chmod +x $PKSCLI
    $PKSCLI login -a $PKS_URL --client-name $PKS_CLIENT --client-secret $PKS_SECRET --skip-ssl-validation
