---
platform: linux


inputs:
- name: config # contains the env file with target OpsMan Information
- name: vars # variable files to be made available
- name: secrets
  optional: true
- name: custom-tasks


params:
  NSXT_INFRA_CONFIG_FILE: nsx-infra.yml
  ACTUALLY_DELETE_NAT_RULES: false


run:
  path: bash
  args:
  - "-c"
  - |
    set -eu

    export NSXUSERNAME=$(yq -t r $NSXT_INFRA_CONFIG_FILE 'nsxt_admin_username')
    export NSXPASSWORD=$(yq -t r $NSXT_INFRA_CONFIG_FILE 'nsxt_admin_password')
    export NSXHOSTNAME=$(yq -t r $NSXT_INFRA_CONFIG_FILE 'nsxt_manager')

    set -eux

    source custom-tasks/tasks/functions/nsxt.sh
    source custom-tasks/tasks/functions/nsxt-yml.sh

    Delete_Logical_Switches $NSXT_INFRA_CONFIG_FILE
    Delete_T1_Routers $NSXT_INFRA_CONFIG_FILE
    Delete_T0_NAT_Rules $NSXT_INFRA_CONFIG_FILE $ACTUALLY_DELETE_NAT_RULES
    Delete_IP_Pools $NSXT_INFRA_CONFIG_FILE
    Delete_IP_Blocks $NSXT_INFRA_CONFIG_FILE
    Delete_Load_Balancers $NSXT_INFRA_CONFIG_FILE
