---
platform: linux


inputs:
- name: config # contains the env file with target OpsMan Information
- name: vars # variable files to be made available
- name: secrets
  optional: true
- name: custom-tasks


params:
  NSXT_INFRA_CONFIG_FILE: nsx-infra.yml
  ACTUALLY_DELETE_NAT_RULES: false


run:
  path: bash
  args:
  - "-c"
  - |
    set -eu
    yq --version

    export NSXUSERNAME=$(yq eval '.nsxt_admin_username' $NSXT_INFRA_CONFIG_FILE )
    export NSXPASSWORD=$(yq eval '.nsxt_admin_password' $NSXT_INFRA_CONFIG_FILE )
    export NSXHOSTNAME=$(yq eval '.nsxt_manager' $NSXT_INFRA_CONFIG_FILE )

    #set -eux

    source custom-tasks/tasks/functions/nsxt4.sh
    source custom-tasks/tasks/functions/nsxt-yml.sh

    Delete_T1_Gateways $NSXT_INFRA_CONFIG_FILE
    Delete_Segments $NSXT_INFRA_CONFIG_FILE
    Delete_IP_Pools $NSXT_INFRA_CONFIG_FILE
    Delete_IP_Blocks $NSXT_INFRA_CONFIG_FILE
    Delete_T0_NAT_Rules $NSXT_INFRA_CONFIG_FILE
