vsphere_templates_folder: BOSH/PKS/templates
vsphere_disks_folder: pks-disks
vsphere_mgmtaz_cluster: attic
vsphere_mgmtaz_resource_pool: PKS-MGMT
vsphere_mgmtaz_host_group: ""
vsphere_az1_cluster: attic
vsphere_az1_resource_pool: PAS
vsphere_az1_host_group: HOST2
vsphere_az2_cluster: attic
vsphere_az2_resource_pool: PAS
vsphere_az2_host_group: HOST3
vsphere_az3_cluster: attic
vsphere_az3_resource_pool: PAS
vsphere_az3_host_group: HOST1
pks_mgmt_network: PKS-MGMT
pks_mgmt_gateway: 10.16.11.1
pks_mgmt_network_cidr: 10.16.11.0/24
pks_mgmt_network_reserved: 10.16.11.1-10.16.11.11

max_threads: 5
vsphere_datastore: EQL-THIN01
vsphere_datacenter: LAB
dns: 192.168.100.50,192.168.100.150
ntp: 192.168.100.50,192.168.100.1
vsphere_vms_folder: BOSH/PKS/VMs/
vcenter_hostname: corevcsa1.ragazzilab.com
vcenter_userid: administrator@vsphere.local
nsx_hostname: corensxmgr.ragazzilab.com
diego_cell/insecure_docker_registry_list: ""
syslog_address: syslog.ragazzilab.com
syslog_port: 514
syslog_protocol: udp
post_deploy_enabled: true
