properties.auth_mode: db_auth
properties.hostname: harbor.pks.ragazzilab.com
network_name: PKS-MGMT
service_network: PKS_MGMT
singleton_availability_zone: PKS-MGMT
other_availability_zones: [PKS-MGMT]
