pivotal-container-service_pks_tls.cert_pem: ((pivotal-container-service_pks_tls.cert_pem))
pivotal-container-service_pks_tls.private_key_pem: ((pivotal-container-service_pks_tls.private_key_pem))
properties_cloud_provider_vsphere_vcenter_master_creds_password: ((properties_cloud_provider_vsphere_vcenter_master_creds_password))
properties_nsx_api_ca_cert: ((nsx_ca_cert))
properties_network_selector_nsx_nsx-t-superuser-certificate.cert_pem: ((properties_network_selector_nsx_nsx-t-superuser-certificate.cert_pem))
properties_network_selector_nsx_nsx-t-superuser-certificate.private_key_pem: ((properties_network_selector_nsx_nsx-t-superuser-certificate.private_key_pem))

properties_cloud_provider_vcenter_dc: LAB
properties_cloud_provider_vcenter_ds: EQL-THIN01
properties_cloud_provider_vcenter_ip: corevcsa1.ragazzilab.com
properties_cloud_provider_vcenter_vms: BOSH/PKS/VMs
properties_network_selector: nsx
properties_network_selector_nsx-t-host: corensxmgr.ragazzilab.com
properties_network_selector_nsx_cloud-config-dns: 192.168.100.50,192.168.100.150
properties_network_selector_nsx_floating-ip-pool-ids: 91ae51a7-1550-41c1-bb37-6533fe153390
properties_network_selector_nsx_ip-block-id: fe35b421-a184-426d-b671-2adc2b731929
properties_network_selector_nsx_nodes-ip-block-id: 8a4fd33b-6da5-46c5-bd38-565685ba5d31
properties_network_selector_nsx_lb_size_large_supported: false
properties_network_selector_nsx_lb_size_medium_supported: true
properties_network_selector_nsx_nat_mode: true
properties_network_selector_nsx_network_automation: true
properties_network_selector_nsx_nsx-t-insecure: true
properties_network_selector_nsx_t0-router-id: 8bc98e0c-17ec-43b7-9819-a8f9a8c4233f
properties_network_selector_nsx_vcenter_cluster: attic
properties_pks-vrli_enabled: enabled
properties_pks-vrli_enabled_host: syslog.ragazzilab.com
properties_pks-vrli_enabled_skip_cert_verify: true
properties_pks-vrops: disabled
properties_pks_api_hostname: api.pks.ragazzilab.com
az1_name: AZ1
az2_name: AZ2
az3_name: AZ3
properties_worker_max_in_flight: 1
network_name: PKS-MGMT
service_network: PKS-MGMT
singleton_availability_zone: MGMT
properties_cloud_provider_vsphere_vcenter_master_creds_identity: administrator@vsphere.local

properties_plan1_selector_active_name: small
properties_plan1_selector_value: "Plan Active"
properties_plan1_selector_active_allow_privileged_containers: true
properties_plan1_selector_active_description: "1 master 1 worker"
properties_plan1_selector_active_master_az_placement: [AZ1]
properties_plan1_selector_active_master_instances: 1
properties_plan1_selector_active_master_persistent_disk_type: "10240"
properties_plan1_selector_active_max_worker_instances: 3
properties_plan1_selector_active_worker_instances: 1
properties_plan1_selector_active_worker_az_placement: [AZ1,AZ2,AZ3]
properties_plan1_selector_active_admission_plugins: [deny_escalating_exec]
properties_plan1_selector_active_master_vm_type: medium.disk
properties_plan1_selector_active_worker_vm_type: medium.disk
properties_plan1_selector_active_errand_vm_type: micro

properties_plan2_selector_active_name: medium
properties_plan2_selector_value: "Plan Active"
properties_plan2_selector_active_allow_privileged_containers: true
properties_plan2_selector_active_description: "1 master 3 workers"
properties_plan2_selector_active_master_az_placement: [AZ1]
properties_plan2_selector_active_master_instances: 1
properties_plan2_selector_active_master_persistent_disk_type: "10240"
properties_plan2_selector_active_max_worker_instances: 3
properties_plan2_selector_active_worker_instances: 1
properties_plan2_selector_active_worker_az_placement: [AZ1,AZ2,AZ3]
properties_plan2_selector_active_admission_plugins: [deny_escalating_exec]
properties_plan2_selector_active_master_vm_type: medium.disk
properties_plan2_selector_active_worker_vm_type: medium.disk
properties_plan2_selector_active_errand_vm_type: micro

properties_plan3_selector_active_name: large
properties_plan3_selector_value: "Plan Active"
properties_plan3_selector_active_allow_privileged_containers: true
properties_plan3_selector_active_description: "3 masters 3 workers"
properties_plan3_selector_active_master_az_placement: [AZ1,AZ2,AZ3]
properties_plan3_selector_active_master_instances: 3
properties_plan3_selector_active_master_persistent_disk_type: "10240"
properties_plan3_selector_active_max_worker_instances: 3
properties_plan3_selector_active_worker_instances: 3
properties_plan3_selector_active_worker_az_placement: [AZ1,AZ2,AZ3]
properties_plan3_selector_active_admission_plugins: [deny_escalating_exec]
properties_plan3_selector_active_master_vm_type: medium.disk
properties_plan3_selector_active_worker_vm_type: medium.disk
properties_plan3_selector_active_errand_vm_type: micro
