---
# code_snippet multiple-product-interpolate-creds start yaml
# This task is used in multiple jobs
# The yaml anchor "*interpolate-creds" is used in its place
interpolate-creds: &interpolate-creds
  image: platform-automation-image
  file: platform-automation-tasks/tasks/credhub-interpolate.yml
  params:
    CREDHUB_CLIENT: ((credhub_client))
    CREDHUB_SECRET: ((credhub_secret))
    CREDHUB_SERVER: ((credhub_server))
    CREDHUB_CA_CERT: ((credhub_ca_cert))
    PREFIX: '/foundation/((foundation))'
    INTERPOLATION_PATHS: "((foundation))/env ((foundation))/vars"
    SKIP_MISSING: true
  input_mapping:
    files: configuration
  output_mapping:
    interpolated-files: interpolated-creds

s3_credentials_binaries: &s3_credentials_binaries
  access_key_id: ((access_key_id))
  secret_access_key: ((secret_access_key))
  endpoint: ((s3.endpoint))
  bucket: ((s3.buckets_pivnet_products))
  region_name: ((s3.region_name))
  skip_ssl_verification: true


resources:
# - name: platform-automation
#   type: pivnet
#   source:
#     api_token: ((pivnet_token))
#     product_slug: platform-automation

- name: platform-automation-tasks
  type: s3
  source:
    <<: *s3_credentials_binaries
    regexp: platform-automation-tasks-(.*).zip

- name: platform-automation-image
  type: s3
  source:
    <<: *s3_credentials_binaries
    regexp: platform-automation-image-(.*).tgz

- name: configuration
  type: git
  source:
    uri: ((config_github_repo))
    branch: ((config_github_branch))
    username: ((github_username))
    password: ((github_token))
    paths: ["((foundation))"]


jobs:
- name: update-configs
  serial: true
  plan:
  - get: configuration
  - get: platform-automation-image
    params:
      unpack: true
  - get: platform-automation-tasks
    params:
      unpack: true
  - task: interpolate-creds
    <<: *interpolate-creds

  - task: configure-pas
    image: platform-automation-image
    file: platform-automation-tasks/tasks/configure-product.yml
    input_mapping:
      config: configuration
      env: interpolated-creds
      vars: interpolated-creds
    params:
      CONFIG_FILE: ((foundation))/config/cf.yml
      VARS_FILES: |
        vars/((foundation))/vars/cf-defaults.yml
        vars/((foundation))/vars/cf-vars.yml
        vars/((foundation))/vars/cf-errands.yml
      ENV_FILE: ((foundation))/env/env.yml

  - task: configure-pasw
    image: platform-automation-image
    file: platform-automation-tasks/tasks/configure-product.yml
    input_mapping:
      config: configuration
      env: interpolated-creds
      vars: interpolated-creds
    params:
      CONFIG_FILE: ((foundation))/config/cf.yml
      VARS_FILES: |
        vars/((foundation))/vars/pas-windows-defaults.yml
        vars/((foundation))/vars/pas-windows-vars.yml
        vars/((foundation))/vars/pas-windows-errands.yml
      ENV_FILE: ((foundation))/env/env.yml

  - task: configure-healthwatch
    image: platform-automation-image
    file: platform-automation-tasks/tasks/configure-product.yml
    input_mapping:
      config: configuration
      env: interpolated-creds
      vars: interpolated-creds
    params:
      CONFIG_FILE: ((foundation))/config/p-healthwatch.yml
      VARS_FILES: |
        vars/((foundation))/vars/p-healthwatch-defaults.yml
        vars/((foundation))/vars/p-healthwatch-vars.yml
        vars/((foundation))/vars/p-healthwatch-errands.yml
      ENV_FILE: ((foundation))/env/env.yml

  # - task: configure-mysql
  #   image: platform-automation-image
  #   file: platform-automation-tasks/tasks/configure-product.yml
  #   input_mapping:
  #     config: configuration
  #     env: interpolated-creds
  #     vars: interpolated-creds
  #   params:
  #     CONFIG_FILE: ((foundation))/config/mysql.yml
  #     VARS_FILES: |
  #       vars/((foundation))/vars/mysql-defaults.yml
  #       vars/((foundation))/vars/mysql-vars.yml
  #       vars/((foundation))/vars/mysql-errands.yml
  #     ENV_FILE: ((foundation))/env/env.yml
