cloud_controller/apps_domain: apps.pas.ragazzilab.com
cloud_controller/system_domain: system.pas.ragazzilab.com
mysql_monitor/recipient_email: brian@ragazzilab.com
network_name: deployment
security_acknowledgement: X
singleton_availability_zone: AZ1
ha_proxy/skip_cert_verify: true
az1_name: AZ1
az2_name: AZ2
az3_name: AZ3
credhub_key_encryption_passwords_0/name: credhub
networking_poe_ssl_certs_0/name: wildcard
credhub_key_encryption_passwords_0/primary: true
stack_migration_acknowledgement: X
tcp_router_instances: 0
router_instances: 1
compute_instances: 1
router_additional_vm_extensions: [pcf_web_vm_extension]
control_additional_vm_extensions: [pcf_ssh_vm_extension]
tcp_router_additional_vm_extensions: [pcf_tcp_vm_extension]
deploy-autoscaler_post_deploy_state: on
deploy-notifications-ui_post_deploy_state: on
deploy-notifications_post_deploy_state: on
metric_registrar_smoke_test_post_deploy_state: off
nfsbrokerpush_post_deploy_state: on
push-apps-manager_post_deploy_state: on
push-usage-service_post_deploy_state: on
smbbrokerpush_post_deploy_state: off
smoke_tests_post_deploy_state: on
test-autoscaling_post_deploy_state: on
diego_cell/insecure_docker_registry_list: ""
