vsphere_templates_folder: BOSH/PAS/templates
vsphere_disks_folder: pas-disks
vsphere_mgmtaz_cluster: attic
vsphere_mgmtaz_resource_pool: PAS-MGMT
vsphere_mgmtaz_host_group: ""
vsphere_az1_cluster: attic
vsphere_az1_resource_pool: PAS
vsphere_az1_host_group: HOST2
vsphere_az2_cluster: attic
vsphere_az2_resource_pool: PAS
vsphere_az2_host_group: HOST3
vsphere_az3_cluster: attic
vsphere_az3_resource_pool: PAS
vsphere_az3_host_group: HOST1
infrastructure_network: PAS-INFRA
infrastructure_gateway: 10.16.21.1
infrastructure_network_cidr: 10.16.21.0/24
infrastructure_network_reserved: 10.16.21.1-10.16.21.20
deployment_network: PAS-DEPLOYMENT
deployment_network_cidr: 10.16.22.0/24
deployment_network_reserved: 10.16.22.1-10.16.22.20
deployment_gateway: 10.16.22.1
services_network: PAS-SERVICES
services_network_cidr: 10.16.23.0/24
services_network_reserved: 10.16.23.1-10.16.23.20
services_gateway: 10.16.23.1
vsphere_datastore: EQL-THIN01
vsphere_datacenter: LAB
dns: 192.168.100.50,192.168.100.150
ntp: 192.168.100.50,192.168.100.1
vsphere_vms_folder: BOSH/PAS/VMs/
vcenter_hostname: corevcsa1.ragazzilab.com
vcenter_userid: administrator@vsphere.local
nsx_hostname: corensxmgr.ragazzilab.com
diego_cell/insecure_docker_registry_list: ""
syslog_address: syslog.ragazzilab.com
syslog_port: 514
syslog_protocol: udp
