az-configuration:
- name: AZ1
  clusters:
  - cluster: attic
    resource_pool: PKS
  iaas_configuration_guid: ed0891766863efbcfa70
- name: AZ2
  clusters:
  - cluster: attic
    resource_pool: PKS
  iaas_configuration_guid: ed0891766863efbcfa70
- name: AZ3
  clusters:
  - cluster: attic
    resource_pool: PKS
  iaas_configuration_guid: ed0891766863efbcfa70
- name: PKS-MGMT
  clusters:
  - cluster: attic
    resource_pool: PKS-MGMT
  iaas_configuration_guid: ed0891766863efbcfa70
iaas-configurations:
- additional_cloud_properties: {}
  bosh_disk_path: ((iaas-configurations_0_bosh_disk_path))
  bosh_template_folder: ((iaas-configurations_0_bosh_template_folder))
  bosh_vm_folder: ((iaas-configurations_0_bosh_vm_folder))
  datacenter: ((iaas-configurations_0_datacenter))
  disk_type: ((iaas-configurations_0_disk_type))
  ephemeral_datastores_string: ((iaas-configurations_0_ephemeral_datastores_string))
  name: ((iaas-configurations_0_name))
  nsx_address: ((iaas-configurations_0_nsx_address))
  nsx_ca_certificate: ((iaas-configurations_0_nsx_ca_certificate))
  nsx_mode: ((iaas-configurations_0_nsx_mode))
  nsx_networking_enabled: ((iaas-configurations_0_nsx_networking_enabled))
  nsx_password: ((iaas-configurations_0_nsx_password))
  nsx_username: ((iaas-configurations_0_nsx_username))
  persistent_datastores_string: ((iaas-configurations_0_persistent_datastores_string))
  ssl_verification_enabled: ((iaas-configurations_0_ssl_verification_enabled))
  vcenter_host: ((iaas-configurations_0_vcenter_host))
  vcenter_password: ((iaas-configurations_0_vcenter_password))
  vcenter_username: ((iaas-configurations_0_vcenter_username))
network-assignment:
  network:
    name: PKS-MGMT
  other_availability_zones: []
  singleton_availability_zone:
    name: PKS-MGMT
networks-configuration:
  icmp_checks_enabled: true
  networks:
  - name: PKS-MGMT
    subnets:
    - iaas_identifier: PKS-MGMT
      cidr: 10.16.11.0/24
      dns: 192.168.100.50,192.168.100.150
      gateway: 10.16.11.1
      reserved_ip_ranges: 10.16.11.1-10.16.11.11
      availability_zone_names:
      - AZ1
      - AZ2
      - AZ3
      - PKS-MGMT
properties-configuration:
  director_configuration:
    blobstore_type: local
    bosh_recreate_on_next_deploy: false
    bosh_recreate_persistent_disks_on_next_deploy: false
    database_type: internal
    director_worker_count: 5
    encryption: []
    hm_emailer_options:
      enabled: false
    hm_pager_duty_options:
      enabled: false
    identification_tags: {}
    job_configuration_on_tmpfs: false
    keep_unreachable_vms: false
    local_blobstore_options:
      tls_enabled: true
    max_threads: 8
    ntp_servers_string: 192.168.100.1
    post_deploy_enabled: true
    resurrector_enabled: true
    retry_bosh_deploys: false
    skip_director_drain: false
  dns_configuration: []
  security_configuration:
    generate_vm_passwords: ((properties-configuration_security_configuration_generate_vm_passwords))
    opsmanager_root_ca_trusted_certs: false
    trusted_certificates: |-
      -----BEGIN CERTIFICATE-----
      MIIDUTCCAjmgAwIBAgIVAMczTVB4cYCA+37RsHl/L65Sv6ibMA0GCSqGSIb3DQEB
      CwUAMB8xCzAJBgNVBAYTAlVTMRAwDgYDVQQKDAdQaXZvdGFsMB4XDTE5MDUxODE5
      MTQ0MFoXDTIzMDUxOTE5MTQ0MFowHzELMAkGA1UEBhMCVVMxEDAOBgNVBAoMB1Bp
      dm90YWwwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDSGCuIBhKEeEpu
      QdsdfLUzhWkywgoKVPD1eATYOaj0AxrGQAsd2+WTzEEK+X0UKqHwJj6JKg6dRR8c
      XrZcK0blye+IWbcbGNuvBcpdXCzifX1Zgbg+3F/mpiHz8YFPa6vlwJkux0OHIDuW
      Z9yrGWPB8DzEx9VbeJ310BoK9LpnTbaQzb/Vf73+5+skiusA7LhkpEBgDDqgK0op
      1Umv0il97ReohpQAl5cdUYhJWoBYxqLWN53+jPPMdBTzcq+NsRI/Pw2VIQcZBSOL
      mf4v1jIpbFkJszdWG9tg2Zkl0qFISqvM8OpDVNsBQKdiuCcQ5ceMETenbo1idSnV
      tgZsqCx5AgMBAAGjgYMwgYAwHQYDVR0OBBYEFDccJablnQPSPY5GKagAVU3ebWzv
      MB8GA1UdIwQYMBaAFDccJablnQPSPY5GKagAVU3ebWzvMB0GA1UdJQQWMBQGCCsG
      AQUFBwMCBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MA4GA1UdDwEB/wQEAwIB
      BjANBgkqhkiG9w0BAQsFAAOCAQEAmcozWRdHhv9lPOD6ZVc4dLs6DAPKwfcj2PJH
      L2BUU+HgoZC02helYJrRCiioha4VjR8Rp+eYTua7Pgg+WJHFF1hjC54GML2l+zt6
      EIoz0Iw0tD0aqcYuZuHpYAB7Kg3hogTJfeRHnG33HhAPG2Px/Yc9a8tE40r7kn/k
      /e7M/6qTDzhbmyeb5sE800Q7w2c7tC5c/3MQhH2JRxEenPxdAPuRMYgb9hVv6Sbr
      PMBej9CnVuBCO1iXGzessDmoO1bvAA9OONsFHCDBUP9xQhLB6O41jXPtMQrNvjN/
      UXqUalkljaYvONFEU0cuCxFjcQ+ET6RZBPdaacg5r/anRDxYIQ==
      -----END CERTIFICATE-----
  syslog_configuration:
    address: syslog.ragazzilab.com
    enabled: true
    forward_debug_logs: false
    port: "514"
    tls_enabled: false
    transport_protocol: udp
resource-configuration:
  compilation:
    instances: automatic
    instance_type:
      id: automatic
  director:
    instances: automatic
    persistent_disk:
      size_mb: automatic
    instance_type:
      id: automatic
vmextensions-configuration: []
