properties_cloud_provider: vSphere
properties_log_sink_resources_deploy: true
properties_metric_sink_resources_deploy: true
properties_network_selector: flannel
properties.network_selector.nsx.lb_size_large_supported: true
properties.network_selector.nsx.lb_size_medium_supported: true
properties.network_selector.nsx.nat_mode: true
properties.network_selector.nsx.network_automation: true
properties.network_selector.nsx.nsx-t-insecure: false
properties.pks-vrli: disabled
properties.pks-vrli.enabled.skip_cert_verify: false
properties.pks-vrli.enabled.use_ssl: true
properties.pks-vrops: disabled
properties.uaa_oidc: false
properties.uaa_pks_cli_access_token_lifetime: 864000
properties.uaa_pks_cli_refresh_token_lifetime: 1728000
properties.wavefront: disabled
properties.worker_max_in_flight: 1
resource-config.persistent_disk: automatic
resource-config.instance_type: automatic
errand-config.delete-all-clusters: true
errand-config.pks-nsx-t-precheck: true
errand-config.smoke-tests: false
errand-config.update-all-service-instances: false
errand-config.wavefront-alert-creation: false
errand-config.wavefront-alert-deletion: false
