properties_cloud_provider: vSphere
properties_log_sink_resources_deploy: true
properties_metric_sink_resources_deploy: true
properties_network_selector: flannel
properties_network_selector_nsx_lb_size_large_supported: true
properties_network_selector_nsx_lb_size_medium_supported: true
properties_network_selector_nsx_nat_mode: true
properties_network_selector_nsx_network_automation: true
properties_network_selector_nsx_nsx-t-insecure: false
properties_pks-vrli_enabled: disabled
properties_pks-vrli_enabled_skip_cert_verify: false
properties_pks-vrli_enabled_use_ssl: true
properties_pks-vrops: disabled
properties_uaa_oidc: false
properties_uaa_pks_cli_access_token_lifetime: 864000
properties_uaa_pks_cli_refresh_token_lifetime: 1728000
properties_wavefront: disabled
properties_worker_max_in_flight: 1
resource-config_persistent_disk: automatic
resource-config_instance_type: automatic
errand-config_delete-all-clusters: true
errand-config_pks-nsx-t-precheck: true
errand-config_smoke-tests: false
errand-config_update-all-service-instances: false
errand-config_wavefront-alert-creation: false
errand-config_wavefront-alert-deletion: false
