product-name: VMware-NSX-T
product-properties:
  .properties.container_ip_blocks:
    value:
    - cidr: ((properties.container_ip_blocks_cidr))
      name: ((properties.container_ip_blocks_name))
  .properties.enable_snat:
    value: ((properties.enable_snat))
  .properties.exit_on_disconnection:
    selected_option: ((properties.exit_on_disconnection))
    value: ((properties.exit_on_disconnection))
  .properties.foundation_name:
    value: ((properties.foundation_name))
  .properties.log_dropped_traffic:
    value: ((properties.log_dropped_traffic))
  .properties.ncp_debug_log:
    value: ((properties.ncp_debug_log))
  .properties.nsx_api_ca_cert:
    value: ((properties.nsx_api_ca_cert))
  .properties.nsx_api_managers:
    value: ((properties.nsx_api_managers))
  .properties.nsx_auth:
    selected_option: ((properties.nsx_auth))
    value: ((properties.nsx_auth))
  .properties.nsx_auth.simple.nsx_api_password:
    value:
      secret: ((properties_nsx_auth_simple_nsx_api_password.secret))
  .properties.nsx_auth.simple.nsx_api_user:
    value: ((properties.nsx_auth_simple_nsx_api_user))
  .properties.nsx_node_agent_debug_log:
    value: ((properties.nsx_node_agent_debug_log))
  .properties.overlay_tz:
    value: ((properties.overlay_tz))
  .properties.subnet_prefix:
    value: ((properties.subnet_prefix))
  .properties.tier0_router:
    value: ((properties.tier0_router))
