# harbor_admin_password: ((harbor_admin_password))
# harbor_server_cert_key_cert_pem: ((harbor_server_cert_key_cert_pem))
# harbor_server_cert_key_private_key_pem: ((harbor_server_cert_key_private_key_pem))
# harbor_server_cert_ca_pem: ((harbor_server_cert_ca_pem))
